package basic.calculator;

/**
 *
 * @author mahmud
 */
public class Calculator extends javax.swing.JFrame {

    double _1st, _2nd, result;
    String operation;
    String answer;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        butttonbackspace = new javax.swing.JButton();
        buttton4 = new javax.swing.JButton();
        buttton1 = new javax.swing.JButton();
        buttton0 = new javax.swing.JButton();
        buttton7 = new javax.swing.JButton();
        buttton5 = new javax.swing.JButton();
        buttton2 = new javax.swing.JButton();
        butttondot = new javax.swing.JButton();
        buttton8 = new javax.swing.JButton();
        butttonclear = new javax.swing.JButton();
        buttton6 = new javax.swing.JButton();
        buttton3 = new javax.swing.JButton();
        butttonequal = new javax.swing.JButton();
        buttton9 = new javax.swing.JButton();
        buttton00 = new javax.swing.JButton();
        butttonmulti = new javax.swing.JButton();
        butttondiv = new javax.swing.JButton();
        butttonpercent = new javax.swing.JButton();
        butttonminus = new javax.swing.JButton();
        butttonplus = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        butttonbackspace.setBackground(new java.awt.Color(0, 102, 51));
        butttonbackspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttonbackspace.setForeground(new java.awt.Color(255, 255, 255));
        butttonbackspace.setText("<--");
        butttonbackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonbackspaceActionPerformed(evt);
            }
        });

        buttton4.setBackground(new java.awt.Color(0, 0, 0));
        buttton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton4.setForeground(new java.awt.Color(255, 255, 255));
        buttton4.setText("4");
        buttton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton4ActionPerformed(evt);
            }
        });

        buttton1.setBackground(new java.awt.Color(0, 0, 0));
        buttton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton1.setForeground(new java.awt.Color(255, 255, 255));
        buttton1.setText("1");
        buttton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton1ActionPerformed(evt);
            }
        });

        buttton0.setBackground(new java.awt.Color(0, 0, 0));
        buttton0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton0.setForeground(new java.awt.Color(255, 255, 255));
        buttton0.setText("0");
        buttton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton0ActionPerformed(evt);
            }
        });

        buttton7.setBackground(new java.awt.Color(0, 0, 0));
        buttton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton7.setForeground(new java.awt.Color(255, 255, 255));
        buttton7.setText("7");
        buttton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton7ActionPerformed(evt);
            }
        });

        buttton5.setBackground(new java.awt.Color(0, 0, 0));
        buttton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton5.setForeground(new java.awt.Color(255, 255, 255));
        buttton5.setText("5");
        buttton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton5ActionPerformed(evt);
            }
        });

        buttton2.setBackground(new java.awt.Color(0, 0, 0));
        buttton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton2.setForeground(new java.awt.Color(255, 255, 255));
        buttton2.setText("2");
        buttton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton2ActionPerformed(evt);
            }
        });

        butttondot.setBackground(new java.awt.Color(0, 0, 0));
        butttondot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttondot.setForeground(new java.awt.Color(255, 255, 255));
        butttondot.setText(".");
        butttondot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttondotActionPerformed(evt);
            }
        });

        buttton8.setBackground(new java.awt.Color(0, 0, 0));
        buttton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton8.setForeground(new java.awt.Color(255, 255, 255));
        buttton8.setText("8");
        buttton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton8ActionPerformed(evt);
            }
        });

        butttonclear.setBackground(new java.awt.Color(0, 102, 51));
        butttonclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttonclear.setForeground(new java.awt.Color(255, 255, 255));
        butttonclear.setText("C");
        butttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonclearActionPerformed(evt);
            }
        });

        buttton6.setBackground(new java.awt.Color(0, 0, 0));
        buttton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton6.setForeground(new java.awt.Color(255, 255, 255));
        buttton6.setText("6");
        buttton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton6ActionPerformed(evt);
            }
        });

        buttton3.setBackground(new java.awt.Color(0, 0, 0));
        buttton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton3.setForeground(new java.awt.Color(255, 255, 255));
        buttton3.setText("3");
        buttton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton3ActionPerformed(evt);
            }
        });

        butttonequal.setBackground(new java.awt.Color(0, 0, 0));
        butttonequal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttonequal.setForeground(new java.awt.Color(255, 255, 255));
        butttonequal.setText("=");
        butttonequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonequalActionPerformed(evt);
            }
        });

        buttton9.setBackground(new java.awt.Color(0, 0, 0));
        buttton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton9.setForeground(new java.awt.Color(255, 255, 255));
        buttton9.setText("9");
        buttton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton9ActionPerformed(evt);
            }
        });

        buttton00.setBackground(new java.awt.Color(0, 102, 51));
        buttton00.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttton00.setForeground(new java.awt.Color(255, 255, 255));
        buttton00.setText("00");
        buttton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton00ActionPerformed(evt);
            }
        });

        butttonmulti.setBackground(new java.awt.Color(0, 102, 51));
        butttonmulti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttonmulti.setForeground(new java.awt.Color(255, 255, 255));
        butttonmulti.setText("*");
        butttonmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonmultiActionPerformed(evt);
            }
        });

        butttondiv.setBackground(new java.awt.Color(0, 102, 51));
        butttondiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttondiv.setForeground(new java.awt.Color(255, 255, 255));
        butttondiv.setText("/");
        butttondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttondivActionPerformed(evt);
            }
        });

        butttonpercent.setBackground(new java.awt.Color(0, 102, 51));
        butttonpercent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttonpercent.setForeground(new java.awt.Color(255, 255, 255));
        butttonpercent.setText("%");
        butttonpercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonpercentActionPerformed(evt);
            }
        });

        butttonminus.setBackground(new java.awt.Color(0, 102, 51));
        butttonminus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttonminus.setForeground(new java.awt.Color(255, 255, 255));
        butttonminus.setText("-");
        butttonminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonminusActionPerformed(evt);
            }
        });

        butttonplus.setBackground(new java.awt.Color(0, 102, 51));
        butttonplus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butttonplus.setForeground(new java.awt.Color(255, 255, 255));
        butttonplus.setText("+");
        butttonplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonplusActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttton7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttton0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttton8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(butttondot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butttonbackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butttonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttton9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butttonequal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttton00, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butttonminus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butttonpercent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butttondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butttonmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butttonplus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(butttonbackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(butttonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttton7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttton0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttton8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(butttondot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttton00, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttton9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butttonequal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butttonplus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butttonminus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butttonmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butttondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butttonpercent, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void butttonbackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonbackspaceActionPerformed
        String butttonbackspace = null;
        if (textField.getText().length() > 0) {
            StringBuilder str = new StringBuilder(textField.getText());
            str.deleteCharAt(textField.getText().length() - 1);
            butttonbackspace = str.toString();
            textField.setText(butttonbackspace);

        }
    }//GEN-LAST:event_butttonbackspaceActionPerformed

    private void buttton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton4ActionPerformed
        String number = textField.getText() + buttton4.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton4ActionPerformed

    private void buttton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton1ActionPerformed
        String number = textField.getText() + buttton1.getText();
        textField.setText(number);

    }//GEN-LAST:event_buttton1ActionPerformed

    private void buttton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton0ActionPerformed
        String number = textField.getText() + buttton0.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton0ActionPerformed

    private void buttton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton7ActionPerformed
        String number = textField.getText() + buttton7.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton7ActionPerformed

    private void buttton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton5ActionPerformed
        String number = textField.getText() + buttton5.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton5ActionPerformed

    private void buttton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton2ActionPerformed
        String number = textField.getText() + buttton2.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton2ActionPerformed

    private void butttondotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttondotActionPerformed
        String number = textField.getText() + butttondot.getText();
        textField.setText(number);
    }//GEN-LAST:event_butttondotActionPerformed

    private void buttton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton8ActionPerformed
        String number = textField.getText() + buttton8.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton8ActionPerformed

    private void butttonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonclearActionPerformed
        textField.setText(null);
    }//GEN-LAST:event_butttonclearActionPerformed

    private void buttton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton6ActionPerformed
        String number = textField.getText() + buttton6.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton6ActionPerformed

    private void buttton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton3ActionPerformed
        String number = textField.getText() + buttton3.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton3ActionPerformed

    private void butttonequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonequalActionPerformed
        String answer;
        _2nd = Double.parseDouble(textField.getText());
        if (operation == "+") {
            result = _1st + _2nd;
            answer = String.format("%.0f", result);
            textField.setText(answer);
        } else if (operation == "-") {
            result = _1st - _2nd;
            answer = String.format("%.0f", result);
            textField.setText(answer);
        } else if (operation == "*") {
            result = _1st * _2nd;
            answer = String.format("%.0f", result);
            textField.setText(answer);
        } else if (operation == "/") {
            result = _1st / _2nd;
            answer = String.format("%.2f", result);
            textField.setText(answer);
        } else if (operation == "%") {
            result = _1st % _2nd;
            answer = String.format("%.2f", result);
            textField.setText(answer);
        }
    }//GEN-LAST:event_butttonequalActionPerformed

    private void buttton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton9ActionPerformed
        String number = textField.getText() + buttton9.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton9ActionPerformed

    private void buttton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton00ActionPerformed
        String number = textField.getText() + buttton00.getText();
        textField.setText(number);
    }//GEN-LAST:event_buttton00ActionPerformed

    private void butttonmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonmultiActionPerformed
        _1st = Double.parseDouble(textField.getText());
        textField.setText("");
        operation = "*";
    }//GEN-LAST:event_butttonmultiActionPerformed

    private void butttondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttondivActionPerformed
        _1st = Double.parseDouble(textField.getText());
        textField.setText("");
        operation = "/";
    }//GEN-LAST:event_butttondivActionPerformed

    private void butttonpercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonpercentActionPerformed
        _1st = Double.parseDouble(textField.getText());
        textField.setText("");
        operation = "%";
    }//GEN-LAST:event_butttonpercentActionPerformed

    private void butttonminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonminusActionPerformed
        _1st = Double.parseDouble(textField.getText());
        textField.setText("");
        operation = "-";
    }//GEN-LAST:event_butttonminusActionPerformed

    private void butttonplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonplusActionPerformed
        _1st = Double.parseDouble(textField.getText());
        textField.setText("");
        operation = "+";
    }//GEN-LAST:event_butttonplusActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton buttton0;
    private javax.swing.JButton buttton00;
    private javax.swing.JButton buttton1;
    private javax.swing.JButton buttton2;
    private javax.swing.JButton buttton3;
    private javax.swing.JButton buttton4;
    private javax.swing.JButton buttton5;
    private javax.swing.JButton buttton6;
    private javax.swing.JButton buttton7;
    private javax.swing.JButton buttton8;
    private javax.swing.JButton buttton9;
    private javax.swing.JButton butttonbackspace;
    private javax.swing.JButton butttonclear;
    private javax.swing.JButton butttondiv;
    private javax.swing.JButton butttondot;
    private javax.swing.JButton butttonequal;
    private javax.swing.JButton butttonminus;
    private javax.swing.JButton butttonmulti;
    private javax.swing.JButton butttonpercent;
    private javax.swing.JButton butttonplus;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables

}
